config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'page#home'
  

  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
	mount_uploader :image, ImageDiaryUploader

	def self.recent
		order("created_at DESC")
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.recent.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:title, :body, :image)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :diary_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :diary_body %>
  </div>

  <div class="field">
    <%= form.file_field :image, id: :diary_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<div id="diary-background">

  <div class='container' id="thingsandstuff">
    <p id="notice"><%= notice %></p>

    <div> 
      <div id="blog-header">
        <h1 class="blog-title">An Unexpected Journey</h1>
        <p class="lead blog-description">The Official Digital Diary for Cami and Gordon's Married Life</p>
        <%= link_to 'New Diary', new_diary_path, class: 'TACO' %>
      </div>
    </div>
  </div>

  <div class="container">
    <% @diaries.each do |diary| %>
      <div class="blog-post">
        <h2 class="blog-post-title"><%= link_to diary.title, diary %></h2>
        <p class="blog-post-meta"><%= diary.created_at %></p>
        <br>

        <%= image_tag diary.image, width: '400px', height: '250px' %>
        <p>
        <%= link_to 'Edit', edit_diary_path(diary) %>
        <%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div> 
    <% end %>

  </div>
</div>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<div class="row">
		
			<p class="show-page-image">
			  <%= image_tag @diary.image %>
			</p>
		
		
		  <strong>Title:</strong>
		<p>
		  <%= @diary.title %>
		</p>

		  <strong>Body:</strong>
		<p>
		  <%= @diary.body %>
		</p>

		
		
	</div>

	<%= link_to 'Edit', edit_diary_path(@diary) %> |
	<%= link_to 'Back', diaries_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalDairyGc</title>
    
    <%= render 'shared/nav' %>
  
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/page/home.html.erb
<body class="home_background">
	<p class="container home_saying">I made this for my lovely wife and want her to know that I love her very much and let her know that I'm thinking of her.</p>	

</body>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md nav_background">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <p class="navbar-brand" href="#">Cami + Gordon</p>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "diaries", diaries_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "login", new_user_session_path, class: "nav-link" %>
      </li>
    </ul>

    <span class="navbar-text cute-saying">
      <%= render 'shared/nav_helper' %>
    </span>
  </div>
</nav>

app/views/shared/_nav_helper.html.erb
<link href="https://fonts.googleapis.com/css?family=Courgette|Gloria+Hallelujah|Indie+Flower" rel="stylesheet">
<% arr = [
	'My one and only',
	'I love you',
	'My forever girl',
	'Your weirdo loves you',
	'Taco Tuesday!',
	'Hey hot stuff',
	'Hello Beautiful',
	'Hey sexy Lady'
] %>



<p><%= arr.sample %></p>